"""remove relationship

Revision ID: 113a0c604eff
Revises: e6ced8bf0c22
Create Date: 2024-06-29 08:19:40.924343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113a0c604eff'
down_revision = 'e6ced8bf0c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow',
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('borrow_date', sa.DATE(), nullable=False),
    sa.Column('is_returned', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='fk_borrow_book_id_book'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='fk_borrow_member_id_member'),
    sa.PrimaryKeyConstraint('member_id', 'book_id', name='pk_borrow')
    )
    # ### end Alembic commands ###
