"""member model

Revision ID: cbf6bde1c0d7
Revises: 
Create Date: 2024-06-29 06:05:44.422522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf6bde1c0d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('penalized_until', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member')),
    sa.UniqueConstraint('code', name=op.f('uq_member_code'))
    )
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
