"""borrow

Revision ID: d468eb4b1e6b
Revises: 113a0c604eff
Create Date: 2024-06-29 08:24:17.342050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd468eb4b1e6b'
down_revision = '113a0c604eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_borrow_book_id_book')),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_borrow_member_id_member')),
    sa.PrimaryKeyConstraint('book_id', 'member_id', name=op.f('pk_borrow'))
    )
    op.create_index(op.f('ix_borrow_book_id'), 'borrow', ['book_id'], unique=False)
    op.create_index(op.f('ix_borrow_member_id'), 'borrow', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_member_id'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_book_id'), table_name='borrow')
    op.drop_table('borrow')
    # ### end Alembic commands ###
