"""borrow relationship

Revision ID: e6ced8bf0c22
Revises: 551d1fc9bfc5
Create Date: 2024-06-29 07:47:51.880854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ced8bf0c22'
down_revision = '551d1fc9bfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('borrow_date', sa.Date(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_borrow_book_id_book')),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('fk_borrow_member_id_member')),
    sa.PrimaryKeyConstraint('member_id', 'book_id', name=op.f('pk_borrow'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrow')
    # ### end Alembic commands ###
